# configuracion mediante archivo yaml importando de un documento .env y puerto
spring:
  port: ${PORT}
  config:
    import: optional:file:.env[.properties]
  # Datos de la conexion a base de datos mediante enviroment.
  datasource:
    url: ${URL}/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
  # Configuracion de jpa e hibernate.
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  # Configuracion de enviroment de clave para crear 
  # la llave secret y para el token de los test. 
  application:
    secret:
      key: ${SECRET_KEY}
      test: ${SECRET_TEST_KEY}

